import os
import signal
import subprocess
import time
import uuid
from pathlib import Path

from core import config, device_info
from core.i18n import t
from core import version_manager

_processes = {}  # name -> Popen
_stack = []      # ordered server names for console stack


def default_properties(
    name: str,
    motd: str = None,
    max_players: int = 10,
    gamemode: str = "survival",
    difficulty: str = "easy",
    pvp: bool = True,
    online_mode: bool = False,
    port: int = 25565,
) -> dict:
    return {
        "motd": motd or (f"\u00a7b{name}\u00a7r \u00a77| MD Server"),
        "server-port": port,
        "online-mode": "true" if online_mode else "false",
        "max-players": max_players,
        "gamemode": gamemode,
        "difficulty": difficulty,
        "pvp": "true" if pvp else "false",
        "view-distance": 8,
        "simulation-distance": 6,
        "level-name": "world",
        "spawn-protection": 16,
        "enable-query": "false",
        "enforce-secure-profile": "false",
    }


def write_properties(server_dir, name, props: dict = None):
    props = props or default_properties(name)
    Path(server_dir).mkdir(parents=True, exist_ok=True)
    lines = ["#Minecraft server properties", "#Generated by MD Server", ""]
    existing = {}
    prop_file = os.path.join(server_dir, "server.properties")
    if os.path.exists(prop_file):
        with open(prop_file, "r", encoding="utf-8", errors="ignore") as f:
            for line in f:
                if "=" in line and not line.strip().startswith("#"):
                    k, v = line.split("=", 1)
                    existing[k.strip()] = v.strip()
    merged = {**existing, **props}
    for k, v in merged.items():
        lines.append(f"{k}={str(v).lower() if isinstance(v, bool) else v}")
    with open(prop_file, "w", encoding="utf-8") as f:
        f.write("\n".join(lines) + "\n")


def read_property(server_dir, key, default=None):
    prop_file = os.path.join(server_dir, "server.properties")
    if not os.path.exists(prop_file):
        return default
    with open(prop_file, "r", encoding="utf-8", errors="ignore") as f:
        for line in f:
            if "=" in line and not line.strip().startswith("#"):
                k, v = line.split("=", 1)
                if k.strip() == key:
                    return v.strip()
    return default


def write_eula(server_dir, accept=True):
    Path(server_dir).mkdir(parents=True, exist_ok=True)
    with open(os.path.join(server_dir, "eula.txt"), "w", encoding="utf-8") as f:
        f.write("#By changing the setting below to TRUE you are indicating your agreement to our EULA\n")
        f.write("#https://aka.ms/MinecraftEULA\n")
        f.write(f"eula={'TRUE' if accept else 'FALSE'}\n")


def create_folder_structure(server_dir, srv_type: str):
    base = ["world", "logs", "backups", "config", "libraries"]
    if srv_type in ("fabric", "forge"):
        base.append("mods")
    if srv_type == "fabric":
        base.append("config")
    if srv_type == "forge":
        base.append("config")
    for d in base:
        Path(os.path.join(server_dir, d)).mkdir(parents=True, exist_ok=True)


def install_vanilla(server_dir, version: str, progress_cb=None):
    from core.downloader import DownloadState, download_with_retry
    info = version_manager.get_vanilla_server_info(version)
    dest = os.path.join(server_dir, "server.jar")
    ds = DownloadState(f"Minecraft {version} (server.jar)", info["url"], dest,
                       sha1=info.get("sha1"), expected_size=0)
    ok = download_with_retry(ds, progress_cb=progress_cb)
    if not ok:
        raise RuntimeError(ds.error or f"failed_download:{dest}")
    return {"jar": "server.jar", "java": info.get("java", 17)}


def install_fabric(server_dir, version: str, loader: str, progress_cb=None):
    from core.downloader import DownloadState, download_with_retry, download
    from core.ui import progress as ui_progress
    try:
        url = version_manager.fabric_installer_url()
        name = version_manager.fabric_installer_name()
    except Exception:
        url = "https://meta.fabricmc.net/v2/versions/installer/1.0.1/installer/jar"
        name = "fabric-installer-1.0.1.jar"
    dest = os.path.join(server_dir, name)
    ds = DownloadState("Fabric installer", url, dest)
    if not download(ds, progress_cb=progress_cb):
        if ds.error:
            raise RuntimeError(ds.error)

    console = ui_progress.console
    console.print(f"[cyan]▸ {t('wizard.downloading')}: [bold]fabric-server-launch.jar[/bold] ...[/cyan]")
    with console.status("Fabric server ..."):
        import subprocess
        r = subprocess.run(
            ["java", "-jar", dest, "server", "-mcversion", version, "-loader", loader, "-dir", server_dir],
            capture_output=True, text=True, cwd=server_dir, timeout=600,
        )
    if r.returncode != 0:
        raise RuntimeError(f"fabric_install_failed:{r.stderr[-400:]}")

    launch = os.path.join(server_dir, "fabric-server-launch.jar")
    if not os.path.exists(launch):
        candidates = [f for f in os.listdir(server_dir) if f.startswith("fabric-server")]
        launch = os.path.join(server_dir, candidates[0]) if candidates else None
    if not launch:
        raise RuntimeError("fabric_launch_missing")
    return {"jar": os.path.basename(launch), "java": version_manager.java_required(version)}


def install_forge(server_dir, minecraft: str, forge: str, progress_cb=None):
    from core.downloader import DownloadState, download
    from core.ui import progress as ui_progress
    url = version_manager.forge_installer_url(minecraft, forge)
    dest = os.path.join(server_dir, f"forge-{minecraft}-{forge}-installer.jar")
    ds = DownloadState("Forge installer", url, dest)
    if not download(ds, progress_cb=progress_cb):
        if ds.error:
            raise RuntimeError(ds.error)
    console = ui_progress.console
    console.print(f"[cyan]▸ {t('wizard.downloading')}: [bold]forge-{minecraft}-{forge}.jar[/bold] ...[/cyan]")
    with console.status("Forge installServer ..."):
        import subprocess
        r = subprocess.run(["java", "-jar", dest, "--installServer"],
                           capture_output=True, text=True, cwd=server_dir, timeout=900)
    if r.returncode != 0:
        raise RuntimeError(f"forge_install_failed:{r.stderr[-400:]}")

    # find generated server jar
    jar = None
    for f in os.listdir(server_dir):
        if f.startswith(f"forge-{minecraft}-{forge}") and f.endswith(".jar") and "installer" not in f:
            jar = f
    if not jar:
        raise RuntimeError("forge_launch_missing")
    return {"jar": jar, "java": 17}


def build_java_command(server_dir, meta, ram_mb=None, nogui=True):
    ram = ram_mb or meta.get("ram_mb", 2048)
    jar = meta.get("jar", "server.jar")
    cmd = [
        "java",
        f"-Xms{int(ram / 2)}M",
        f"-Xmx{ram}M",
        "-XX:+UseG1GC",
        "-Dfile.encoding=UTF-8",
        "-jar", jar,
    ]
    if nogui:
        cmd.append("nogui")
    return cmd


def start_server(name: str) -> bool:
    server_dir = config.server_dir(name)
    meta = config.load_server_meta(name)
    cmd = build_java_command(server_dir, meta)
    if not os.path.exists(os.path.join(server_dir, meta.get("jar", "server.jar"))):
        return False
    proc = subprocess.Popen(
        cmd,
        cwd=server_dir,
        stdin=subprocess.PIPE,
        stdout=subprocess.PIPE,
        stderr=subprocess.STDOUT,
        text=True,
        bufsize=1,
    )
    _processes[name] = proc
    if name not in _stack:
        _stack.append(name)
    config.set_state(name, "state", "running")
    config.set_state(name, "pid", proc.pid)
    config.set_state(name, "started_at", time.time())
    config.set_state(name, "error", None)
    return True


def get_process(name: str):
    proc = _processes.get(name)
    if proc and proc.poll() is None:
        return proc
    # recover from pid file
    st = config.get_state(name)
    pid = st.get("pid")
    if pid:
        try:
            os.kill(pid, 0)
            if os.path.exists(f"/proc/{pid}"):
                return None  # not managed by this session
        except Exception:
            pass
    if proc:
        _processes.pop(name, None)
    return None


def is_running(name: str) -> bool:
    proc = get_process(name)
    if proc:
        return True
    st = config.get_state(name)
    return st.get("state") == "running" and False


def stop_server(name: str, timeout=40) -> bool:
    proc = get_process(name)
    if not proc:
        return False
    try:
        proc.stdin.write("stop\n")
        proc.stdin.flush()
    except (BrokenPipeError, ValueError):
        pass
    try:
        proc.wait(timeout=timeout)
    except subprocess.TimeoutExpired:
        proc.terminate()
        try:
            proc.wait(timeout=15)
        except subprocess.TimeoutExpired:
            proc.kill()
    _processes.pop(name, None)
    config.set_state(name, "state", "stopped")
    config.set_state(name, "pid", None)
    config.set_state(name, "stopped_at", time.time())
    return True


def send_command(name: str, cmd: str) -> bool:
    proc = get_process(name)
    if not proc:
        return False
    try:
        proc.stdin.write(cmd + "\n")
        proc.stdin.flush()
        return True
    except (BrokenPipeError, ValueError):
        return False


def restart_server(name: str) -> bool:
    stop_server(name)
    time.sleep(2)
    return start_server(name)


def check_dead(name: str):
    proc = get_process(name)
    if proc:
        code = proc.poll()
        if code is not None:
            config.set_state(name, "state", "stopped")
            config.set_state(name, "pid", None)
            config.set_state(name, "exit_code", code)
            return True
    return False


def mark_error(name: str, msg: str):
    config.set_state(name, "state", "error")
    config.set_state(name, "error", msg)


def process_uptime(name: str) -> float:
    st = config.get_state(name)
    s = st.get("started_at")
    if s:
        return time.time() - s
    return 0


def process_pid(name: str):
    st = config.get_state(name)
    return st.get("pid")